### PR TITLE
fix:Use sun & moon icon instead of toggle theme button

### LINKED ISSUE #27: [frontend] Theme Button on Header
Can we use the Sun and Moon button instead of the current one? This one is looking weird and not going with the website

### PR DESCRIPTION
**Pull request by corazoan**
fix issue #27

### CODE REVIEW

File: app/components/toggleSwitches/ToggleThemeSwitch.jsx [hunk 1]
```diff
@@ -1,42 +1,67 @@
 "use client";
 import "./toggleThemeSwitch.css";
```
Comment (anonymous-sidhax) [inline app/components/toggleSwitches/ToggleThemeSwitch.jsx]: Can you remove this import if this is not being used

**Review by anonymous-sidhax — APPROVED** [review]
